version: '2'
services:
    sharelatex:
        restart: always
        image: 192.168.1.10/omega:0.9
        container_name: sharelatex
        depends_on:
            - mongo
            - redis
            - clsi
        privileged: true
        ports:
            - 80:80
            - 443:443
        expose:
            - 3009
        links:
            - mongo
            - redis
            - clsi
        volumes:
            - ~/sharelatex_data:/var/lib/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
            #- /var/clsi/compiles:/var/www/sharelatex/clsi/compiles
        environment:
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            SHARELATEX_REDIS_HOST: redis
            CLSI_HOST: clsi
            FILESTORE_HOST: sharelatex
            SHARELATEX_APP_NAME: Omega
            SHARELATEX_EMAIL_FROM_ADDRESS: omega@levinhansen.dk
            SHARELATEX_EMAIL_SMTP_HOST: 192.168.1.12
            SHARELATEX_EMAIL_SMTP_PORT: 25
            SHARELATEX_EMAIL_SMTP_SECURE: "false"
            SHARELATEX_EMAIL_SMTP_USER: omega@levinhansen.dk
            SHARELATEX_EMAIL_SMTP_PASS: meatfucker
            SHARELATEX_CUSTOM_EMAIL_FOOTER: <div>This system is run with crossed fingers.</div>
            SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: "false"
            SHARELATEX_EMAIL_SMTP_IGNORE_TLS: "true"
            SHARELATEX_ADMIN_EMAIL: omega@levinhansen.dk
            ## Set for SSL via nginx-proxy
            #VIRTUAL_HOST: 103.112.212.22

            SHARELATEX_BEHIND_PROX: "true"

            SHARELATEX_SITE_LANGUAGE: da
            SHARELATEX_SITE_URL: https://omega.levinhansen.dk
            # SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
            # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            # SHARELATEX_ADMIN_EMAIL: support@it.com

            # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            SHARELATEX_RIGHT_FOOTER: '[{"text": "For her kompiler&rsquo; FysikRevy&trade;"} ]'

            # SHARELATEX_EMAIL_FROM_ADDRESS: "team@sharelatex.com"

            # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID: 
            # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY: 

            # SHARELATEX_EMAIL_SMTP_HOST: smtp.mydomain.com
            # SHARELATEX_EMAIL_SMTP_PORT: 587
            # SHARELATEX_EMAIL_SMTP_SECURE: false
            # SHARELATEX_EMAIL_SMTP_USER: 
            # SHARELATEX_EMAIL_SMTP_PASS: 
            # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
            # SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"

            ################
            ## Server Pro ##
            ################

            # SANDBOXED_COMPILES: 'true'
            
            # SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
            # SANDBOXED_COMPILES_HOST_DIR: '/var/clsi/compiles'

            ## Works with test LDAP server shown at bottom of docker compose
            # SHARELATEX_LDAP_URL: 'ldap://ldap:389'
            # SHARELATEX_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
            # SHARELATEX_LDAP_SEARCH_FILTER: '(uid={{username}})'
            # SHARELATEX_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
            # SHARELATEX_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
            # SHARELATEX_LDAP_EMAIL_ATT: 'mail'
            # SHARELATEX_LDAP_NAME_ATT: 'cn'
            # SHARELATEX_LDAP_LAST_NAME_ATT: 'sn'
            # SHARELATEX_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'

            # SHARELATEX_TEMPLATES_USER_ID: "578773160210479700917ee5"

            # SHARELATEX_PROXY_LEARN: "true"

    clsi:
        restart: always
        image: 192.168.1.10/clsi-sharelatex:0.1.2
        container_name: clsi
        expose:
          - 3013
        environment:
          LISTEN_ADDRESS: 0.0.0.0
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - ~/mongo_data:/data/db

    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/redis_data:/data

    # ldap:
    #    restart: always
    #    image: rroemhild/test-openldap
    #    container_name: ldap
    #    expose:
    #        - 389
# nginx-proxy:
#     image: jwilder/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       #- "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - /home/sharelatex/tmp:/etc/nginx/certs
